# Generated by Django 5.2.6 on 2025-09-25 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_azerscode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="genre",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="artist",
            name="price_tag",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="artist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
