# Generated by Django 5.2.6 on 2025-09-25 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_artist_bio_alter_artist_genre_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="media_file",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="portfolios/"),
        ),
        migrations.AlterField(
            model_name="artist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="azerscode",
            name="note",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="notes",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Partially Paid", "Partially Paid"),
                    ("Paid", "Paid"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="azers_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("artist", "Artist"), ("seller", "Seller")], max_length=20
            ),
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(blank=True, max_length=150)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="sellers/"),
                ),
                ("bio", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
