# Generated by Django 5.2.6 on 2025-09-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_portfolio_media_file_portfolio_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="artists/"),
        ),
    ]
