# Generated by Django 5.2.6 on 2025-09-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_artist_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("document", "Document"),
                ],
                default="image",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
