# Generated by Django 5.2.6 on 2025-09-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_user_role_brand_product_service_delete_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="brands/"),
        ),
    ]
