# Generated by Django 6.0.1 on 2026-03-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_brandinquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("fashion", "Fashion"),
                    ("electronics", "Electronics"),
                    ("beauty", "Beauty & Health"),
                    ("art", "Art & Collectibles"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("music", "Music Production"),
                    ("graphics", "Graphic Design"),
                    ("marketing", "Marketing"),
                    ("event", "Event Planning"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
