# Generated by Django 6.0.1 on 2026-03-28 10:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_lead"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="booking",
            name="event_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="booking",
            name="secret_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending Approval"),
                    ("Accepted", "Accepted & Active"),
                    ("Declined", "Declined"),
                    ("Completed", "Gig Finished"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_quote",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="booking",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="core.artist",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Event details, duration, etc."
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Unpaid", "Unpaid"),
                    ("Partially Paid", "Partially Paid (50%)"),
                    ("Paid", "Fully Paid"),
                ],
                default="Unpaid",
                max_length=20,
            ),
        ),
    ]
