# Generated by Django 6.0.1 on 2026-03-29 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_booking_options_booking_event_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="secret_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
