# Generated by Django 6.0.1 on 2026-04-08 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_booking_options_remove_booking_secret_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="guest_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="receiver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_chats",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
