# Generated by Django 6.0.1 on 2026-04-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_conversation_guest_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="subject_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="visitor_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
