# Generated by Django 6.0.1 on 2026-04-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_conversation_subject_type_conversation_visitor_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="chat_images/"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
