# Generated by Django 6.0.1 on 2026-04-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_chatmessage_image_alter_chatmessage_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandinquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("responded", "Responded"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
