# Generated by Django 6.0.1 on 2026-04-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_brandinquiry_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("event_date", models.DateTimeField()),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Physical or Virtual Link", max_length=255
                    ),
                ),
                ("total_capacity", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "requires_photo",
                    models.BooleanField(
                        default=True,
                        help_text="If true, users must upload a photo for the digital pass",
                    ),
                ),
                (
                    "ticket_template",
                    models.ImageField(
                        blank=True,
                        help_text="The blank design we will paste the user face onto",
                        null=True,
                        upload_to="tickets/templates/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "ordering": ("-event_date",),
            },
        ),
        migrations.CreateModel(
            name="TicketPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=200)),
                ("user_photo", models.ImageField(upload_to="ticket_holders/")),
                ("payment_receipt", models.ImageField(upload_to="payment_proofs/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Verifying"),
                            ("approved", "Issued"),
                            ("declined", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("issued_pass_id", models.CharField(blank=True, max_length=50)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="core.ticket",
                    ),
                ),
            ],
        ),
    ]
