# Generated by Django 6.0.1 on 2026-04-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_ticket_ticketpurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketpurchase",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
