# Generated by Django 6.0.1 on 2026-04-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_ticketpurchase_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketpurchase",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
