# Generated by Django 6.0.1 on 2026-09-23 12:42

import core.storage
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_artist_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storage.PortfolioCloudinaryStorage(), upload_to=core.models.portfolio_upload_path),
        ),
    ]
